# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23cc0bdf92f9d48afc3e7967c58c4cca290b13ac3bcf083c90592217ef933d939f978ffb39c9a11da25d020539875d4733cc05b1ebc7ca9aba866f4c48d5c7b5

test:
  secret_key_base: 0dc5b4b252601e2e666bfeecaa2343b1305c7768bd89941f73df9fe1091300b68414f35f8272e1ae3a899117a1c558ce94af74f35d267e00584ff3ed2f0101f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
